### ISSUE TITLE
Unable to run parallel tests on real devices.

### ISSUE THREAD

**Issue by ChethanGKC** [email2vimalraj/appium-stf-example#2] opened 2017-01-26 10:46 UTC
@email2vimalraj - Can you pleas let me know how the tests are running parallel as showed in the video as in the code we are running the tests through single port 4723.

hoping for the early reply, thanks in advance.

**Comment by email2vimalraj** [comment] 2017-01-27 02:08
@ChethanGKC :

That could be because of a small mistake in my committed code. Try updating the `data provider` method be static and execute. 

This is just a wild guess. If not working, kindly share me your code base which I will try to reproduce.

**Comment by ChethanGKC** [comment] 2017-01-31 08:18
thanks @email2vimalraj . i achived parallel execution by using Appium grid. :)

**Comment by email2vimalraj** [comment] 2017-01-31 08:25
Kindly share the community on how did you solve using Appium grid?

**Comment by ChethanGKC** [comment] 2017-02-11 17:05
@email2vimalraj : Sorry for the late reply, I modified above example by below steps.
1. Start selenium standalone server 
2. Opened two or more instance of appium server
3. Passed the device ID and port number

**Closed as completed** 2017-03-06 03:06 UTC
